SELECT 
  [player] as Player, 
  [team] as Team, 
  [position] as Position, 
  [gold_per_minute] as GoldPerMin, 
  [winrate] as WinRate, 
  [counter_pickrate] as CounterPickRate, 
  [kills] as Kills, 
  [deaths] as Deaths, 
  [assists] as Assists, 
  [kda] as KDA, 
  [kp] as KP, 
  [kill_share] as KillShare, 
  [share_team_deaths] as TeamDeathShare, 
  [first_blood_rate] as FirstBloodRate, 
  [gold_diff_10] as GoldDiff@10, 
  [xp_diff_10] as XPDiff@10, 
  [cs_diff_10] as CSDiff@10, 
  [cspm] as CSPerMin, 
  [share_team_deaths_15] as TeamDeathShare@15, 
  [damage_per_minute] as DPM, 
  [share_damage] as DamageShare, 
  [share_team_damage_15] as TeamDamageShare@15, 
  [average_gold_per_minute] as AverageGPM, 
  [gold_share] as GoldShare, 
  [neutral_objectives_stolen] as StolenNeutralObjectives, 
  [wards_per_minute] as WardsPerMin, 
  [control_wards_per_minute] as ControlWardsPerMin, 
  [wards_cleared_per_minute] as WardsClearedPerMin 
FROM 
  [League2022Project].[dbo].[wc_players_main]
